In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr # 파이썬은 숫자를 0부터 센다

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[:5] #0 1 2 3 4

array([0, 1, 2, 3, 4])

In [7]:
arr[3:]  # 3부터 끝까지

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr[0:5] = 100  # broadcasting   0 1 2 3 4  = 100 / 5 6 7 8 9 10
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [12]:
arr = np.arange(0,11)
slice_of_arr = arr[0:6] # 0 1 2 3 4 5 = 99
slice_of_arr[:] = 99
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [18]:
arr_copy = arr.copy()
arr_copy[:] = 200
arr_copy    # 기준이 되는 데이터는 바꾸지 않고 복사해서 쓴다 / 메모리 절약

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [19]:
arr 

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
# mat[row,column] / mat[row][col]

In [22]:
mat = np.array([[5,10,15],[20,25,30],[35,40,45]])
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
mat[0]   # 행렬도 0부터 센다

array([ 5, 10, 15])

In [24]:
mat[1]

array([20, 25, 30])

In [25]:
mat[2]

array([35, 40, 45])

In [26]:
mat[1][1]

25

In [27]:
mat[1,1]

25

In [28]:
mat[0,2]

15

In [29]:
mat[0,[1,2]]

array([10, 15])

In [32]:
mat[:2,1:]   # 0행~1행, 1열~2열

array([[10, 15],
       [25, 30]])

In [35]:
mat[1:3,0:2]   # 1행~2행, 0열~1열

array([[20, 25],
       [35, 40]])

In [36]:
mat[1:,:2]

array([[20, 25],
       [35, 40]])