In [3]:
import numpy as np

In [6]:
# creating numpy array
my_list = [1,2,3]
x = np.array(my_list)
type(x)

numpy.ndarray

In [8]:
 my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [11]:
np.arange(0,5) # array range

array([0, 1, 2, 3, 4])

In [14]:
np.arange(0,13,2)

array([ 0,  2,  4,  6,  8, 10, 12])

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
np.zeros((3,5)) #np.zeros((row,column))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones(4)

array([1., 1., 1., 1.])

In [21]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.linspace(0,10,3) # 시작, 끝, 등간격

array([ 0.,  5., 10.])

In [24]:
np.linspace(0,10,21) # 시작, 끝, 등간격

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
np.random.rand(5,4) # uniform distribution

array([[0.62959565, 0.8495629 , 0.645995  , 0.55045566],
       [0.24528532, 0.23875212, 0.54494396, 0.01190345],
       [0.44414269, 0.5104996 , 0.24379789, 0.32890414],
       [0.46368143, 0.93870894, 0.7873902 , 0.03031104],
       [0.29725864, 0.14631018, 0.70632032, 0.6378382 ]])

In [29]:
np.random.randn(3,5)  # standard normal distribution.

array([[-1.18762342e+00,  4.72916811e-01, -2.22908156e+00,
         8.00715879e-01,  5.40210889e-01],
       [-1.71234748e+00,  1.29458880e-03, -7.80375426e-01,
        -6.17171374e-01,  1.80131824e-01],
       [-5.09313969e-01, -1.93520093e-01,  1.80865607e+00,
        -1.68566170e-01,  2.07808135e-01]])

In [39]:
np.random.randint(1,100,10)  # 1과 99 사이에서 Uniform distribution 으로 10개 난수 추출

array([22,  7, 77, 81, 96,  4, 54, 85, 91, 66])

In [40]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
ranarr

array([36, 37,  0, 10, 30,  9,  4, 30, 42, 44])

In [46]:
arr.shape

(25,)

In [44]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
arr.reshape(5,5).shape

(5, 5)

In [48]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [49]:
arr.reshape(25,1).shape

(25, 1)

In [50]:
arr.dtype

dtype('int32')

In [54]:
ranarr.max() # 최대값을 호출

44

In [55]:
ranarr.argmax() # 최대값이 있는 인덱스 위치

9

In [56]:
ranarr.min() 

0

In [57]:
ranarr.argmin() # 최대값이 있는 인덱스 위치

2