In [1]:
import numpy as np

In [2]:
# Conditional Selection

In [4]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [9]:
bool_arr = arr > 4
arr[bool_arr] # 기존 arr에 True, False 결합하면 True인 원소만 남는 리스트로 바뀐다

array([ 5,  6,  7,  8,  9, 10])

In [10]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [11]:
arr[arr <= 9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])