In [1]:
import numpy as np

In [8]:
arr = np.arange(1,10)

In [13]:
arr1 = arr.reshape(3,3)

In [14]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr1 + arr1

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [16]:
arr1 * arr1

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [18]:
arr1 - arr1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [22]:
arr1 / arr1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
arr1 ** 3

array([[  1,   8,  27],
       [ 64, 125, 216],
       [343, 512, 729]], dtype=int32)

In [25]:
arr1 + 10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [27]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [19]:
arr = np.arange(0,10)

In [20]:
arr / arr  # 첫번째 원소 0으로 나눌 수 없기 때문에 오류 메시지 호출, 문제있는 항목이 nan

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [23]:
1 / arr   # 첫번째 항목은 0으로 나눠서 infinity

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [26]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [28]:
np.max(arr)

9

In [29]:
arr.max() # np.max(arr) 같은 명령

9

In [30]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [31]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [32]:
np.log(arr)

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])